config/routes.rb
Demov3::Application.routes.draw do
  resources :pages

  match '/results', :to => 'searches#results'
  match '/loading', :to =>'searches#loading'
  match '/about', :to =>'pages#about'
  match '/new', :to => 'searches#new'
  match '/contact', :to => 'pages#contact'
  match '/jobs', :to => 'pages#jobs'

root :to => 'searches#new'
resources :results

resources :searches do
	collection do
		get 'new'
		post 'search'
	end
	member do
		get 'results' #equivalent of show
	end
end

end

app/models/inbetweener.rb
class Inbetweener < ActiveRecord::Base

belongs_to :result

attr_accessible :id, :company, :taxi_price, :bus_price, :train_price, :shuttle_price, :start_name, :end_name



end

app/models/page.rb
class Page < ActiveRecord::Base
end

app/models/result.rb
class Result < ActiveRecord::Base
#attr_accessible :id, :real_price, :escore, :route, :start_time, :end_time, :stops, :price_tag, :transportation, :transit_time, :start_date, :end_date
#this is so we can sort on this:
#acts_as_list

attr_accessible :id, :departure, :arrival, :real_price, :escore, :vehicles, :start_date_time, :end_date_time, :start_date, :end_date, :start_time, :end_time, :stops, :price_tag, :transit_time, :start_location, :end_location, :position, :train, :plane, :bus, :ferry

cattr_reader :per_page
@@per_page = 10

has_many :voyages
has_many :inbetweeners

	def self.search(search)
		self.all #for now, change later
	end
	
	
	
	def validvehicles?(params)
		#if (all the vehicles used in this result)
		#are also part of the list of vehicles allowed 
		#by the checkbox
		return true
	
	end

end

app/models/voyage.rb
class Voyage < ActiveRecord::Base
belongs_to :result

attr_accessible :id, :departure, :arrival, :position, :company, :real_price, :escore, :start_time, :end_date, :start_date, :end_time, :stops, :price_tag, :transportation, :transit_time, :start_location, :end_location


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def contact
	@title = "Contact"
  end
  
  def about
	@title = "About"
  end
  
  # GET /pages
  # GET /pages.xml
  def index
    @pages = Page.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @pages }
    end
  end

  # GET /pages/1
  # GET /pages/1.xml
  def show
    @page = Page.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @page }
    end
  end

  # GET /pages/new
  # GET /pages/new.xml
  def new
    @page = Page.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @page }
    end
  end

  # GET /pages/1/edit
  def edit
    @page = Page.find(params[:id])
  end

  # POST /pages
  # POST /pages.xml
  def create
    @page = Page.new(params[:page])

    respond_to do |format|
      if @page.save
        format.html { redirect_to(@page, :notice => 'Page was successfully created.') }
        format.xml  { render :xml => @page, :status => :created, :location => @page }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @page.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /pages/1
  # PUT /pages/1.xml
  def update
    @page = Page.find(params[:id])

    respond_to do |format|
      if @page.update_attributes(params[:page])
        format.html { redirect_to(@page, :notice => 'Page was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @page.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /pages/1
  # DELETE /pages/1.xml
  def destroy
    @page = Page.find(params[:id])
    @page.destroy

    respond_to do |format|
      format.html { redirect_to(pages_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/results_controller.rb
class ResultsController < ApplicationController  

def show

    @result = Result.find(params[:id])
	
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @post }
    end
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def new  
  	#@search = Search.new
	#@results = Results.all	
	
	respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @results }
    end
  
  end
#right now the below function is doing nothing
#eventually we can redirect through this function, instead of results, 
#whichshould computer what to display?
  def search
  	@results = Result.all
    @search = Search.new(params[:post])

    respond_to do |format|
      if @post.save
        format.html { rrender :action => "results" }
        format.xml  { render :xml => @post, :status => :created, :location => @post }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @post.errors, :status => :unprocessable_entity }
      end
    end
  end

  def results
@start_address = params[:start_address]
#@startresults = Result.all
@returnresults = Result.all
@startresults = Result.where("(NOT(CAST(train AS BOOLEAN)) OR :traincheckbox)AND (NOT(CAST(bus AS BOOLEAN)) OR :buscheckbox)AND(NOT(CAST(plane AS BOOLEAN)) OR :planecheckbox)AND(NOT(CAST(ferry AS BOOLEAN)) OR :ferrycheckbox) AND start_location = :start_location AND end_location = :end_location", {:traincheckbox=> params[:traincheckbox], :planecheckbox=> params[:planecheckbox], :buscheckbox=> params[:buscheckbox],:ferrycheckbox=> params[:ferrycheckbox],:taxicheckbox=> params[:taxicheckbox], :start_date => params[:start_date], :end_date=>params[:end_date],:start_location => params[:start_location], :end_location => params[:end_location]}).order(params[:sort])
#@returnresults = Result.where("(NOT(train) OR :traincheckbox)AND (NOT(bus) OR :buscheckbox)AND(NOT(plane) OR :planecheckbox)AND(NOT(ferry) OR :ferrycheckbox) AND start_date = :return_date AND start_location = :end_location AND end_location = :start_location", {:traincheckbox=> params[:traincheckbox], :planecheckbox=> params[:planecheckbox], :buscheckbox=> params[:buscheckbox],:ferrycheckbox=> params[:ferrycheckbox],:taxicheckbox=> params[:taxicheckbox], :start_date => params[:start_date], :return_date=>params[:return_date],:start_location => params[:start_location], :end_location => params[:end_location]}).order(params[:sort])
    respond_to do |format|
      format.html # results.html.erb
      format.xml  { render :xml => @voyage }
	format.js
    end
  end

def inbetweener

end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def sortable(column, title = nil)
		title ||= column.titleize
		css_class = column == sort_column ? "current #{sort_direction}" : nil
		direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
		link_to title, {:sort =>column, :direction => direction}, {:class => css_class}
  end

end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/layouts/_cost.html.erb
						<table>
						<tr>
							<td style="vertical-align:top"><label for="stops">Stops</label></br><img id="stops" src="images/stop.png" tooltip="# of tops"/><%= result.stops %></td>
							<td style="vertical-align:top"><label for="time1">Time</label></br><img id="time1" src="images/time.png" tooltip="# of tops"/><%= result.transit_time %></td>
							
						</tr>
						<tr>
							<td style="vertical-align:top"><label for="pricetag">Price Tag</label><img id="pricetag" src="images/pricetag.jpg" tooltip="Pricetag"/><%= result.price_tag %></td>
							<td style="vertical-align:top"><label for="realcost">Final Price</label><img id="realcost" src="images/dollar.jpg" tooltip="Estimated Total Price"/><%= result.real_price %></td>
							
						</tr>
						</table>

app/views/layouts/_dialog.html.erb
<table>
<% voyages.each do |voyage| %>
	<tr>
		<td> <%= image_tag ("companylogothumbnails/"+voyage.company+".jpg") %></td>
		<td>
			From: <%= voyage.start_location %><br/> 
			To: <%= voyage.end_location %><br/> 
			Departure: <%= voyage.start_time.strftime("%a at %I:%M%p") %>, <%= voyage.start_date.strftime("%m/%d/%y") %>  </br>
			Arrival: <%= voyage.end_time.strftime("%a at %I:%M%p") %>, <%= voyage.end_date.strftime("%m/%d/%y") %>  </br> 
			Transit Time: <%= voyage.transit_time %></td>
		<td> Book this Leg!</td>
	</tr>
<% end %>
</table>
<div class="round explanation">

<div id="inbetweeners1" class="inbetweeners round2">
<h3><a href="#">Inbetweeners</a></h3>
	<div id="inbetween" class="round2">
	<% @inbetweeners = result.inbetweeners %>
		<% @inbetweeners.each do |inbetweener| %>
		<div class="inbetween round2">
			<%= render 'layouts/inbetweener', :inbetweener => inbetweener %>
		</div>
		<% end %>
		<div class="total-tweener round2">
		TOTAL: $40
		</div>
	</div>


</div>
<div id="taxes" class="taxes round2">
<h3><a href="#">Extra Taxes/Visas</a></h3>
	<div class="round2">
		<div id="taxes1" class="round2">
				<div class="explanationtitle">
					Airport Taxes:
				</div>
				<div class="taxdescription">
					None
				</div>
				<div id="taxresult1">
				Estimated Cost: $0
				</div>
		</div>
		<div id="taxes2" class="round2">
				<div class="explanationtitle">
					Visa Info:
				</div>
				<div class="taxdescription">
					Available at border free of charge.
				</div>
				<div id="taxresult2">
				Estimated Cost: $0
				</div>
		</div>

		<div class="total-taxes round2">
		TOTAL: $0
		</div>
	</div>


</div>

</div>
<script>
	$(".tweenresult").each(function(k) {
	$(this).attr("id", "tweenresult" + k);
	});
</script>

app/views/layouts/_footer.html.erb
<div id="footer">
    <ul>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
	  <li><%= link_to "Jobs", jobs_path %></li>
    </ul>
</div>

app/views/layouts/_graph.html.erb
<link href="/stylesheets/visualize.css?1306004945" media="screen" rel="stylesheet" type="text/css" /> 
<link href="/stylesheets/visualize-dark.css?1305838256" media="screen" rel="stylesheet" type="text/css" /> 
<link href="/stylesheets/visualize-light.css?1305875344" media="screen" rel="stylesheet" type="text/css" /> 


	<div id="graph" class="round">
		<table style="display:none">
		<caption>Price Forecasts</caption>
		<thead>
			<tr>
			<td></td>
			<th scope="col">5/25</th>
			<th scope="col">5/26</th>
			<th scope="col">5/27</th>
			<th scope="col">5/28</th>
			<th scope="col">5/29</th>
			<th scope="col">5/30</th>
			<th scope="col">5/31</th>
			<th scope="col">6/1</th>
			<th scope="col">6/2</th>
			<th scope="col">6/3</th>
		</tr>
	</thead>
	<tbody>
		<tr>
			<th scope="row">Price Tag</th>
			<td>190</td>
			<td>160</td>
			<td>40</td>
			<td>120</td>
			<td>30</td>
			<td>70</td>
			<td>30</td>
			<td>70</td>
			<td>30</td>
			<td>70</td>
		</tr>
		<tr>
			<th scope="row">Real Price</th>
			<td>3</td>
			<td>40</td>
			<td>30</td>
			<td>45</td>
			<td>35</td>
			<td>49</td>
			<td>30</td>
			<td>70</td>
			<td>30</td>
			<td>70</td>
		</tr>
	
	</tbody>
</table>
	
	
	</div>

app/views/layouts/_inbetweener.html.erb
		<div class="explanationtitle">
			<%= inbetweener.start_name %> > <%= inbetweener.end_name %>
		</div>

<%= form_tag '/results', :method => 'get', :id => "inbetweeners-transportation-form" do %>
		<div id="choices1">
			<label for="vehicle_type_train">Train </label><%= radio_button_tag 'vehicle_type', 'train', true %>
			<label for="vehicle_type_taxi">Taxi: </label><%= radio_button_tag 'vehicle_type', 'taxi', false %>
			<label for="vehicle_type_bus">Bus: </label><%= radio_button_tag 'vehicle_type', 'bus', false %>
			<label for="vehicle_type_shuttle">Shuttle: </label><%= radio_button_tag 'vehicle_type', 'shuttle', false %>
		</div>

		<div class="tweenresult">
		Estimated Cost: 
		<div id="leg_price" style="display:inline"></div>
			<%= render 'layouts/leg_price' %>

		</div>
<% end %>




<script>
/*$(document).ready(function (){
	$('#vehicle_type_train, #vehicle_type_taxi, #vehicle_type_bus, #vehicle_type_shuttle').live("change", function(){
		$.get($(this).attr('action'), $(this).serialize(), null, "script");
		return false;
		});
		});
*/
</script>

app/views/layouts/_newsidebar.html.erb
<div id="newsideinfo">
		<h3><a href="#">NOTE!!!</a></h3>
			<div class="addspace">
				THE LOCATIONS AND DATES ARE CURRENTLY RESTRICTED! THIS IS A DEMO ONLY!
				Routes you can search:</br>Tallinn > Stockholm, and reverse</br>
				London > Paris, and reverse</br>
				London > Toulouse, and reverse</br>
				New York City > Washington D.C., and reverse</br>
			</div>
		<h3><a href="#"></a></h3>
			<div class="addspace">
				

			</div>
		<h3><a href="#">Real Cost Accounting</a></h3>
			<div class="addspace">
				Uncover deceiving taxes, remote airports, and luggage fees with our real pricing estimate.
			</div>
		<h3><a href="#">Comprehensive Booking</a></h3>
			<div class="addspace">
				Book all legs of the journey from one site.
			</div>
</div>

app/views/layouts/_notaccordion.html.erb
<%= form_tag results_path, :method => 'get', :id=>'searchform', :remote=>true do %> 
	<div id="notaccordion">
		<h3><a href="#">Change Locations</a></h3>
			<div class="addspace">
				<b>Beginning Address:</b>
				<div class="ui-widget">
					<label for="start_address">Street: </label>
					<input id="start_address" name="start_address" class="submittable"/></br>
					<label for="start_location">City: </label>
					<input id="start_location" name="start_location" class="submittable"/></br>
				</div>
				<b>Ending Address:</b>
				<div class="ui-widget">
					<label for="end_address">Street: </label>
					<input id="end_address" name="end_address" class="submittable"/></br>
					<label for="end_location">City: </label>
					<input id="end_location" name="end_location" class="submittable"/></br>
				</div>
			</div>
	
		<h3><a href="#">Flight Times</a></h3>
		<div id="contact" class="addspace">
			<div id="sliders">
						<style>
					#slider-range,#SlideMax,#slider-range2,#SlideMax2{width:180px;}
					#slider-range,#time, #SlideMax, #slider-range2,#time2, #SlideMax2{margin:10px;display:block;}
				</style>
				Departure Time:
				<div id="slider-range"></div>
				<span id="SlideMax"></span>
				<span id="time"></span>
				Return Time:
				<div id="slider-range2"></div>
				<span id="SlideMax2"></span>
				<span id="time2"></span>
			</div>
		</div>
		<h3><a href="#">Stops/Layovers</a></h3>
		<div class="addspace">
			<form name="myform" action="http://www.mydomain.com/myformhandler.cgi" method="POST">
				<div align="center">
					Max # Layovers: 
					<select name="mydropdown">
					<option value="1">1</option>
					<option value="2">2</option>
					<option value="3">3</option>
					<option value="3">4</option>
					<option value="3">5</option>
					</select>
				</div>
			</form>
		</div>
		<h3><a href="#">Change Dates</a></h3>
		<div class="addspace">
			<div class="demo">

			<p>Date: <input type="text" id="datepicker-start" name="start_date" class="submittable"></p>

			</div><!-- End demo -->
			<div class="demo">

			<p>Date: <input type="text" id="datepicker-end" name="return_date" class="submittable"></p>

			</div><!-- End demo -->
		</div>
		<h3><a href="#">Cabin</a></h3>
		<div class="addspace">
			<div id="format">
				<input type="checkbox" id="check1"  class="submittable"/><label for="check1">Economy</label>
				<input type="checkbox" id="check2"  class="submittable"/><label for="check2">Business</label>
				<input type="checkbox" id="check3"  class="submittable"/><label for="check3">First</label>
			</div>
		</div>
	</div>
<% end %>


app/views/layouts/_rightbar.html.erb
<table>
	<tr>
		<td>
			<div id="cart">
				<h1 class="ui-widget-header">Save</h1>
				<div>
					<div class="ui-widget-content">
						<ol>
							<li class="placeholder">Drag Your Favorite Routes Here</li>
						</ol>
					</div>
				</div>
			</div>
		</td>
	</tr>
	<tr>
		<td>
			<% for i in (1..20) %>
				<div class="right-ad-bar">
					<script type="text/javascript"><!--
					google_ad_client = "ca-pub-5609456848181056";
					/* contentbartextad */
					google_ad_slot = "2176448574";
					google_ad_width = 234;
					google_ad_height = 60;
					//-->
					</script>
					<script type="text/javascript"
					src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
					</script>
				</div>
			<% end %>
		</td>
	</tr>
</table>

app/views/layouts/_searchform.html.erb
		<div id="sharing_hide" style="display:block">
				<%= form_tag results_path, :method => 'get', :onsubmit =>"rememberinput('start_location', 'end_location')", :id => 'searchform' do %>
						<div id="locations" style="margin-top: 20px;">
							<div id="start-address" class="round">
								START ADDRESS
								<div id="startstreet">
									<label for="start_address">Street </label><input id="start_address" name="start_address"></br>
								</div>
								<div id="startcity">
									<label for="start">City </label>
									<div class="ui-widget"style="display:inline">
										<input style="width:150px;" id="start" name="start_location">
									</div>
								</div>
								
							</div>
							<div id="end-address" class="round">
								END ADDRESS
								<div id="endstreet">
									<label for="end_address">Street </label><input id="end_address" name="end_address" ></br>
								</div>
								<div id="endcity">								
									<label for="end">City</label>
									<div class="ui-widget" style="display:inline">
										<input style="width:150px;" id="end" name="end_location">
									</div></br>
								</div>						
							</div>
</br></br></br></br></br>
						</div>
</br>
						<div id="dates" style="margin-top: 20px;" class="round">
							<div id="start_date_box" style="display:inline"> 
								<label for="start_date" style="font-weight:bold font-family: Arial">Start Date</label>
								<input type="text" name="start_date" id="start_date" />
							</div>
							<div id="end_date_hide" style="display:inline; float:right;" >
								<label for="return_date">Return Date</label>
								<input type="text" name="return_date" id="return_date" />
							</div>
						</div>
						</br>
						
						<%= render 'layouts/transportationtable' %>
						
						<div id="choice4">
						<table style="font-weight:bold; padding: 10px;">
							<tr>
								<td style="width: 180px; align: center;">
									<input type="checkbox" id="nonstopcheckbox" name="nonstopcheckbox" value="Non-stops only" align="middle"/>
									<label for="nonstopcheckbox" >Non-stops only</label>
								</td>
								<td style="width: 200px;" >
									<input type="checkbox" id="flexdates" name="flexdatescheckbox" value="My dates are flexible" align="middle"/>
									<label for="flexdates">My dates are flexible</label>
								</td>
								<td>
									<select name="travelers">
									  <option value="1">1 Traveler</option>
									  <option value="2">2 Travelers</option>
									  <option value="3">3 Travelers</option>
									  <option value="4">4 Travelers</option>
									  <option value="5">5 Travelers</option>
									  <option value="6">6 Travelers</option>
									</select>
									
								</td>
								<td>
									<select name="bags">
									  <option value="1">1 Checked Bag</option>
									  <option value="2">2 Checked Bags</option>
									  <option value="3">3 Checked Bags</option>
									  <option value="4">4 Checked Bags</option>
									</select>
									
								</td>
							</tr>
						</table>
						</div>
						<div class="actions">
							<div class="demo"> 
								<%= submit_tag "Search" %>
							</div> 
						</div>

					<% end %>

				</div>
				<div id="coming_soon_hide" style="display:none">
				Coming Soon
				</br>
				</br>
				</br>
				</br>
				</br>
				</br>
				</br>
				</br>
				</br>
				</br>
				</br>
				</br>
				</br>
				</br>
				</br>
				</br>
				</br>
				
				</div>

app/views/layouts/_voyagetable.html.erb
	<div id="price-sort-to">
		
		<button><%= link_to "Convenience", results_path(:sort => "escore", :start_address => params[:start_address], :start_location => params[:start_location], :end_address => params[:end_address], :end_location => params[:end_location], :start_date => params[:start_date], :return_date => params[:return_date], :traincheckbox => params[:traincheckbox], :planecheckbox => params[:planecheckbox], :ferrycheckbox => params[:ferrycheckbox], :buscheckbox => params[:buscheckbox], :traincheckbox => params[:traincheckbox], :travelers => params[:travelers], :bags => params[:bags]) %></button>
		<button><%= link_to "RealPrice", results_path(:sort => "real_price", :start_address => params[:start_address], :start_location => params[:start_location], :end_address => params[:end_address], :end_location => params[:end_location], :start_date => params[:start_date], :return_date => params[:return_date], :traincheckbox => params[:traincheckbox], :planecheckbox => params[:planecheckbox], :ferrycheckbox => params[:ferrycheckbox], :buscheckbox => params[:buscheckbox], :traincheckbox => params[:traincheckbox], :travelers => params[:travelers], :bags => params[:bags]) %></button>
		<button><%= link_to "Stops", results_path(:sort => "stops", :start_address => params[:start_address], :start_location => params[:start_location], :end_address => params[:end_address], :end_location => params[:end_location], :start_date => params[:start_date], :return_date => params[:return_date], :traincheckbox => params[:traincheckbox], :planecheckbox => params[:planecheckbox], :ferrycheckbox => params[:ferrycheckbox], :buscheckbox => params[:buscheckbox], :traincheckbox => params[:traincheckbox], :travelers => params[:travelers], :bags => params[:bags])%></button>
		<button><%= link_to "Time", results_path(:sort => "transit_time", :start_address => params[:start_address], :start_location => params[:start_location], :end_address => params[:end_address], :end_location => params[:end_location], :start_date => params[:start_date], :return_date => params[:return_date], :traincheckbox => params[:traincheckbox], :planecheckbox => params[:planecheckbox], :ferrycheckbox => params[:ferrycheckbox], :buscheckbox => params[:buscheckbox], :traincheckbox => params[:traincheckbox], :travelers => params[:travelers], :bags => params[:bags]) %></button>
	</div>
	<div id="results">
       
			<table class="round">
			  <tr>
				<th style="vertical-align:top; display:none">Efficiency Score</th>
				<th style="vertical-align:top; display:none">Real Price</th> 
				<th style="vertical-align:top; display:none">Transit Time</th>
				<th style="vertical-align:top; display:none">Stops</th>
				<th style="vertical-align:top; display:none">Display</th>
				
			  </tr>
			<% total = 0 %>
			
			<% @startresults.each do |result| %>
				
				<% @voyages = result.voyages %>
					  <tr>
						<td style="vertical-align:top; display:none"><%= result.escore%></td>
						<td style="vertical-align:top; display:none"><%= result.real_price %></td>

						<td style="vertical-align:top; display:none"><%= result.transit_time %></td>
						<td style="vertical-align:top; display:none"><%= result.stops %></td>
						<td class="dragonlythis">
							<div class="round" id="voyage">
								<div class="round2" id="itinerary">
									<% @voyages.each do |voyage| %>
										<%= image_tag(voyage.transportation+".jpg", :tooltip => "From:"+voyage.start_location+"<br/> 
										To:"+voyage.end_location+"<br/> 
										Departure:"+voyage.start_time.strftime("%a at %I:%M%p")+", "+voyage.start_date.strftime("%m/%d/%y")+" </br>
										Arrival:"+voyage.end_time.strftime("%a at %I:%M%p")+", "+voyage.end_date.strftime("%m/%d/%y")+"</br> 
										Transit Time: "+voyage.transit_time.to_s) %>
									<% end %>	
									<div id="details" class="round">
									<% start_ad = params[:start_address] %>
								
									<%= link_to 'GO', URI.escape('results/'+result.id.to_s+'?start_address='+params[:start_address]+','+params[:start_location]+'&end_address='+params[:end_address]+','+params[:end_location]+'&departure='+result.departure+'&arrival='+result.arrival), :class =>"ui-state-default ui-corner-all gotoresult" %>

									</div>
							
									<div class="round2" id="info">
									Departure: <%= result.start_time.strftime("%a at %I:%M%p") %>, <%= result.start_date.strftime("%m/%d/%y") %>  </br>
									Arrival: <%= result.end_time.strftime("%a at %I:%M%p") %>, <%= result.end_date.strftime("%m/%d/%y") %>  </br>
									</div>
								</div>
								<div class="round2" id="cost">
									<%= render 'layouts/cost', :result => result %>
								</div>
							</div>
						</td>
					  </tr>
				
			<% end %>
			<script type="text/javascript">
				$(".details-button").each(function(i) {
					$(this).attr("id", "details-button" + i);
				});
				$(".dialog").each(function(k) {
					$(this).attr("id", "dialog" + k);
				});
				
			</script>
	
			</table>


 </div>
	

app/views/layouts/_voyagetabs.html.erb
<div id="tabs">
		<ul>
			<li><a href="#tabs-1">To</a></li>
			<li><a href="#tabs-2">Return</a></li>
			<li><a href="#tabs-3">Add</a></li>
		</ul>
		<div id="tabs-1">
			<%= render 'layouts/voyagetable' %>
		</div>
		<div id="tabs-2">
			
		</div>
		<div id="tabs-3">
			Coming Soon
		</div>
</div>

app/views/pages/_form.html.erb
<%= form_for(@page) do |f| %>
  <% if @page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@page.errors.count, "error") %> prohibited this page from being saved:</h2>

      <ul>
      <% @page.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pages/contact.html.erb
<div class="page-explanation round">
<h1>Contact</h1>
<p>
David Litwak </br>
litwak1@gmail.com </br>
http://www.davidlitwak.com </br>
http://www.litwakrecommends.com </br>

</p>
</div>

app/views/pages/edit.html.erb
<h1>Editing page</h1>

<%= render 'form' %>

<%= link_to 'Show', @page %> |
<%= link_to 'Back', pages_path %>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/pages/index.html.erb
<h1>Listing pages</h1>

<table>
  <tr>
    <th>Title</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @pages.each do |page| %>
  <tr>
    <td><%= page.title %></td>
    <td><%= link_to 'Show', page %></td>
    <td><%= link_to 'Edit', edit_page_path(page) %></td>
    <td><%= link_to 'Destroy', page, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Page', new_page_path %>

app/views/pages/new.html.erb
<h1>New page</h1>

<%= render 'form' %>

<%= link_to 'Back', pages_path %>

app/views/pages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @page.title %>
</p>


<%= link_to 'Edit', edit_page_path(@page) %> |
<%= link_to 'Back', pages_path %>

app/views/searches/inbetweener.js.erb
$("#leg_price").html("<%= escape_javascript(render("layouts/leg_price")) %>")